"""
Derivative GP for thermal flux q(s,T); namely, outputs dq/ds and dq/dT.

Model places one scalar Matern GP prior on the latent flux q and conditions
on noisy observations of its first derivatives, d = [dq/ds(Z_s), dq/dT(Z_T)]^T.

Since both derivative components are generated by differentiating the same scalar
covariance kernel, posterior means form a conservative field which defines one flux
surface up to an additive constant. A single anchor, q(s_a, T_a) = q_a, fixes this
constant. 

Let k_theta be the Matern kernel, and let L_s, L_T denote differentiation wrt s and T. 
The derivative-data covariacne is given by: 

    K_dd = [[L_s L_s' k, L_s L_T' k],
            [L_T L_s' k, L_T L_T' k]]

With propagated finite-difference noise covariance matrix Sigma_d, deriv regularization
lambda_d, and jitter epsilon, fitting uses:

    A = K_dd + Sigma_d + (lambda_d + epsilon)I, 
    alpha = A^{-1}(d - m_d),

where m_d = [-k_ref, 0]^T is the physics-based derivative prior mean. Kernel var and
ARD lengthscales are selected by minimizing derivative negative log marginal likelihood
(i.e. argmaxes of the log likelihood). 

Predictions are given by: 

    q_s(x) = -k_ref + K_{s,d}(x) alpha, 
    q_T(x) =          K_{T,d}(x) alpha, 

with the appropriate standardization factors restored. The flux can be reconstucted either
directly from the GP cross-covariance and anchor, or by integrating the learned derivative field
from the anchor using GL quadrature. 

Matern nu = 3/2 is the default because it is the least-smooth common half-integer Matern 
kernel supporting first mean-square derivatives. Matern nu=5/2 remains available when a smoother
derivative field and Newton Jacobian are preferred. Experiments can be run using this nu param
simply by not specifying nu = 3/2 (the code retains older implementations of the kernel and its
derivatives using nu = 5/3). 

RMK: This script includes dynamic refitting. Namely, we update the posterior whenever our testing
interface indicates model uncertainty in predicting derivative (measured by the posterior variances
associated to derivative quantities), and enable the capacity to do so in either the FIFO or distance-based 
framework. 

References: 
1. Solak et al. (2003); Derivative Observations in Gaussian Process Models of 
Dynamical Systems
2. Rasmussen and Williams (2006); Gaussian Processes for Machine Learning
3. Sarkka (2011); Linear Operators and Stochastic Partial Differential Equations
in Gaussian Process Regression

TO DO: 
- need to keep deriv regularization below learned noise levels 

"""

from pathlib import Path

import numpy as np
from numpy.polynomial.legendre import leggauss
from scipy.linalg import cho_solve
from scipy.optimize import minimize

class DerivativeGPFluxST:
    """fit a single latent flux GP to noisy dq/ds and dq/dT observations.
    model preserves integrability because both derivative components are obtained
    from one scalar kernel. "reg derivative" adds isotropic derivative-field regulairzation
    to standardized covariance system. "jitter" is a separate numerical Cholesky safeguard."""
    def __init__(
        self, 
        X_dq_ds,
        dq_ds,
        X_dq_dT,
        dq_dT,
        derivative_noise_covariance,
        anchor_s,
        anchor_T,
        anchor_q,
        kernel_nu=1.5,
        k_ref=None, # diffusivity constant reference; if unknown, stably estimated as median -dq_ds
        min_conductivity=0.0,
        reg_derivative=0.0, # defauls no reg; can be added to precision diagonal 
        jitter=1e-10,
        n_restarts_optimizer=0,
        random_state=42,
        max_cache_size=None, # counts paired deirv centers
    ):
        self.kernel_nu = float(kernel_nu)
        self.min_conductivity = float(min_conductivity)
        self.reg_derivative = float(reg_derivative)
        self.jitter = float(jitter)
        self.n_restarts_optimizer = int(n_restarts_optimizer)
        self.random_state = int(random_state)
        self.max_cache_size = None if max_cache_size is None else int(max_cache_size)
        self.posterior_updates_ = 0
        self.total_points_added_ = 0
        self.total_points_dropped_ = 0

        self.fit(
            X_dq_ds,
            dq_ds,
            X_dq_dT,
            dq_dT,
            derivative_noise_covariance,
            anchor_s,
            anchor_T,
            anchor_q,
            k_ref,
        )
    
    @classmethod
    def from_npz(cls, path, **kwargs):
        """load derivative observations, noise covariance, anchor, and local metadata. 
        the npz is produced by the anchor-centered FD field builder. sampling metadata
        are retained for diagnostics, but do not alter the GP posterior once the derivative data
        and covariance have been loaded."""
        path = Path(path)
        with np.load(path, allow_pickle=False) as data:
            model = cls(
                np.asarray(data["X_dq_ds"], dtype=float),
                np.asarray(data["dq_ds"], dtype=float),
                np.asarray(data["X_dq_dT"], dtype=float),
                np.asarray(data["dq_dT"], dtype=float),
                np.asarray(data["derivative_noise_covariance"], dtype=float),
                float(data["anchor_point"][0]),
                float(data["anchor_point"][1]),
                float(data["anchor_q"]),
                **kwargs,
            )
            # metadata produced by the anchor-centered finite-difference builder.
            # these values are retained for local-domain checks and diagnostics;
            # they do not alter the derivative-GP fitting algorithm.
            model.field_path_ = path
            model.sampling_radii_ = np.asarray(data["sampling_radii"], dtype=float)
            model.local_bounds_ = np.asarray(data["local_bounds"], dtype=float)
            model.h_s_ = float(data["h_s"])
            model.h_T_ = float(data["h_T"])
            model.repeats_ = int(data["repeats"])
            model.anchor_q_variance_ = float(data["anchor_q_variance"])
            model.learned_oracle_noise_variance_ = float(
                data["learned_oracle_noise_variance"]
            )
            model.learned_oracle_noise_std_ = float(
                data["learned_oracle_noise_std"]
            )

        return model
    
    def _parts(self, X, Y, variance=None, lengthscales=None):
        """return pairwise offsets and ARD-scaled distance r:
        r^2 = sum_j ((x_j-y_j)/l_j)^2"""
        if variance is None:
            variance = self.variance_
        if lengthscales is None:
            lengthscales = self.lengthscales_
        delta = X[:, None, :] - Y[None, :, :]
        r = np.sqrt(np.sum((delta / lengthscales) ** 2, axis=2))
        return delta, r, float(variance), np.asarray(lengthscales)

    def _K(self, X, Y, variance=None, lengthscales=None):
        """evaluate latent matern covariance k_theta(X,Y)"""
        _, r, variance, _ = self._parts(X, Y, variance, lengthscales)
        if self.kernel_nu == 1.5:
            a = np.sqrt(3.0)
            return variance * (1.0 + a * r) * np.exp(-a * r)
        # defaults kept from the nu = 2.5 case
        a = np.sqrt(5.0)
        return variance * (1.0 + a * r + 5.0 * r**2 / 3.0) * np.exp(-a * r)

    def _dK_dx(self, X, Y, dim, variance=None, lengthscales=None):
        """evaluate partial k(x,y)/partial x_dim analytically"""
        delta, r, variance, ell = self._parts(X, Y, variance, lengthscales)
        if self.kernel_nu == 1.5:
            a = np.sqrt(3.0)
            factor = -variance * a**2 * np.exp(-a * r)
        else:
            # defaults kept from the nu = 2.5 case
            a = np.sqrt(5.0)
            factor = -(a**2 / 3.0) * variance * (1.0 + a * r) * np.exp(-a * r)
        return factor * delta[:, :, dim] / ell[dim] ** 2

    def _dK_dy(self, X, Y, dim, variance=None, lengthscales=None):
        """evaluate partial k(x,y)/partial y_dim = -partial k/partial x_dim"""
        return -self._dK_dx(X, Y, dim, variance, lengthscales)

    def _d2K_dxdy(self, X, Y, dim_x, dim_y, variance=None, lengthscales=None):
        """evaluate deriv covariance partial^2 k/partial(x_i partial y_j); these
        blocks define Cov(q_i(x), q_j(y)) for i,j in {s,T}."""
        delta, r, variance, ell = self._parts(X, Y, variance, lengthscales)
        lx = ell[dim_x]
        ly = ell[dim_y]
        same = float(dim_x == dim_y)

        if self.kernel_nu == 1.5:
            a = np.sqrt(3.0)
            diagonal = a**2 * same / lx**2
            outer = np.zeros_like(r)
            mask = r > 0.0
            outer[mask] = (
                a**3 * delta[:, :, dim_x][mask]
                * delta[:, :, dim_y][mask] / (lx**2 * ly**2 * r[mask]))
            return variance * np.exp(-a * r) * (diagonal - outer)

        # defaults kept from the nu = 2.5 case
        a = np.sqrt(5.0)
        diagonal = (a**2 / 3.0) * (1.0 + a * r) * same / lx**2
        outer = (
            (a**4 / 3.0) * delta[:, :, dim_x]
            * delta[:, :, dim_y] / (lx**2 * ly**2))
        return variance * np.exp(-a * r) * (diagonal - outer)

    def _joint_covariance(self, variance, lengthscales):
        """assemble K_dd for stacked observations [q_s(Z_s), q_T(Z_T)].
        K_dd = [[K_ss K_sT], [K_Ts, K_TT]]"""
        K_ss = self._d2K_dxdy(self.Z_s_, self.Z_s_, 0, 0, variance, lengthscales)
        K_sT = self._d2K_dxdy(self.Z_s_, self.Z_T_, 0, 1, variance, lengthscales)
        K_Ts = self._d2K_dxdy(self.Z_T_, self.Z_s_, 1, 0, variance, lengthscales)
        K_TT = self._d2K_dxdy(self.Z_T_, self.Z_T_, 1, 1, variance, lengthscales)
        K = np.block([[K_ss, K_sT], [K_Ts, K_TT]])
        return 0.5 * (K + K.T)

    def _objective(self, log_parameters):
        """derivative negative log marginal likelihood; for residual vector r and
        A = K_dd + Sigma_d + (lambda_d + epsilon)I: 

            neg log likelihood = 0.5 r^T A^{-1} r + 0.5 log|A| + n/2 log(2*pi)
        
        params are optimized in log space to preserve positivity."""
        variance = np.exp(log_parameters[0])
        lengthscales = np.exp(log_parameters[1:])
        A = self._joint_covariance(variance, lengthscales)
        A += self.noise_covariance_standardized_
        A += (self.reg_derivative + self.jitter) * np.eye(A.shape[0])
        try:
            L = np.linalg.cholesky(A)
        except np.linalg.LinAlgError:
            return 1e100
        alpha = cho_solve((L, True), self.derivative_residual_standardized_)
        return float(
            0.5 * self.derivative_residual_standardized_ @ alpha
            + np.sum(np.log(np.diag(L)))
            + 0.5 * A.shape[0] * np.log(2.0 * np.pi))

    def fit(
        self,
        X_dq_ds,
        dq_ds,
        X_dq_dT,
        dq_dT,
        derivative_noise_covariance,
        anchor_s,
        anchor_T,
        anchor_q,
        k_ref,
    ):
        """fit the derivative GP and cache Cholesky posterior states. inputs are standardized
        anisotropically. derivative scaling follows: d/dx_j = (q_scale/x_scale_j) d/dz_j,
        so both derivative components are placed on one dimensionless scale. prior mean is 
        q_s = -k_ref, and q_T = 0, whcih makes surrogate revert to a positive effective conductivity
        -q_s = k_ref away from data."""
        X_s = np.asarray(X_dq_ds, dtype=float).reshape(-1, 2)
        X_T = np.asarray(X_dq_dT, dtype=float).reshape(-1, 2)
        d_s = np.asarray(dq_ds, dtype=float).reshape(-1)
        d_T = np.asarray(dq_dT, dtype=float).reshape(-1)
        n_total = d_s.size + d_T.size
        noise_covariance = np.asarray(derivative_noise_covariance, dtype=float)
        self.X_dq_ds_raw_ = X_s.copy()
        self.dq_ds_raw_ = d_s.copy()
        self.X_dq_dT_raw_ = X_T.copy()
        self.dq_dT_raw_ = d_T.copy()
        self.derivative_noise_covariance_raw_ = noise_covariance.copy()
        if self.max_cache_size is None:
            self.max_cache_size = int(d_s.size)
        X_all = np.vstack([X_s, X_T])
        self.x_mean_ = X_all.mean(axis=0)
        self.x_scale_ = X_all.std(axis=0)
        self.x_scale_[self.x_scale_ == 0.0] = 1.0
        self.Z_s_ = (X_s - self.x_mean_) / self.x_scale_
        self.Z_T_ = (X_T - self.x_mean_) / self.x_scale_
        self.anchor_s_ = float(anchor_s)
        self.anchor_T_ = float(anchor_T)
        self.anchor_q_ = float(anchor_q)
        if k_ref is None:
            # stable estimation of diffusivity constant as median of d_s
            self.k_ref_ = max(float(np.median(-d_s)), self.min_conductivity, 1e-8)
        else:
            self.k_ref_ = float(k_ref)
        transformed = np.concatenate([d_s * self.x_scale_[0], d_T * self.x_scale_[1]])
        self.q_scale_ = float(np.sqrt(np.mean(transformed**2)))
        if self.q_scale_ == 0.0:
            self.q_scale_ = 1.0
        scale = np.concatenate([
                np.full(d_s.size, self.x_scale_[0] / self.q_scale_),
                np.full(d_T.size, self.x_scale_[1] / self.q_scale_)])
        derivative_values = np.concatenate([d_s, d_T])
        derivative_mean = np.concatenate([np.full(d_s.size, -self.k_ref_), np.zeros(d_T.size)])
        self.derivative_residual_standardized_ = scale * (derivative_values - derivative_mean)
        self.noise_covariance_standardized_ = (scale[:, None] * noise_covariance * scale[None, :])
        bounds = [
            (np.log(1e-4), np.log(1e4)),
            (np.log(0.1), np.log(10.0)),
            (np.log(0.1), np.log(10.0))]
        initial_variance = max(np.var(self.derivative_residual_standardized_), 1e-3)
        starts = [np.log([initial_variance, 1.0, 1.0])]
        rng = np.random.default_rng(self.random_state)
        for _ in range(self.n_restarts_optimizer):
            starts.append(np.array([rng.uniform(a, b) for a, b in bounds]))
        best = None
        for start in starts:
            result = minimize(self._objective, start, method="L-BFGS-B", bounds=bounds)
            if best is None or result.fun < best.fun:
                best = result
        self.variance_ = float(np.exp(best.x[0]))
        self.lengthscales_ = np.exp(best.x[1:])
        self.negative_log_marginal_likelihood_ = float(best.fun)
        A = self._joint_covariance(self.variance_, self.lengthscales_)
        A += self.noise_covariance_standardized_
        A += (self.reg_derivative + self.jitter) * np.eye(n_total)
        A = 0.5 * (A + A.T)
        self.L_ = np.linalg.cholesky(A)
        self.alpha_ = cho_solve((self.L_, True), self.derivative_residual_standardized_)
        self.condition_number_ = float(np.linalg.cond(A))
        self.alpha_norm_ = float(np.linalg.norm(self.alpha_))
        anchor = np.array([[self.anchor_s_, self.anchor_T_]])
        anchor = (anchor - self.x_mean_) / self.x_scale_
        K_anchor = np.hstack([self._dK_dy(anchor, self.Z_s_, 0), self._dK_dy(anchor, self.Z_T_, 1)])
        self.anchor_residual_standardized_ = float((K_anchor @ self.alpha_).item())
        return self

    def _rebuild_cached_posterior(self):
        """recompute derivative posterior with fixed hyperparameters; original input
        scaling, q_scale, k_ref, kernel variance, lengthscales, regularization, and 
        jitter remain unchanged."""
        X_s = self.X_dq_ds_raw_
        X_T = self.X_dq_dT_raw_
        d_s = self.dq_ds_raw_
        d_T = self.dq_dT_raw_
        self.Z_s_ = (X_s - self.x_mean_)/self.x_scale_
        self.Z_T_ = (X_T - self.x_mean_)/self.x_scale_
        scale = np.concatenate([
            np.full(d_s.size, self.x_scale_[0]/self.q_scale_),
            np.full(d_T.size, self.x_scale_[1]/self.q_scale_),
        ])
        derivative_values = np.concatenate([d_s, d_T])
        derivative_mean = np.concatenate([
            np.full(d_s.size, -self.k_ref_),
            np.zeros(d_T.size),
        ])
        self.derivative_residual_standardized_ = scale * (derivative_values - derivative_mean)
        self.noise_covariance_standardized_ = scale[:, None] * self.derivative_noise_covariance_raw_ * scale[None, :]
        A = self._joint_covariance(self.variance_, self.lengthscales_)
        A += self.noise_covariance_standardized_
        A += (self.reg_derivative + self.jitter) * np.eye(A.shape[0])
        A = 0.5 * (A + A.T)
        self.L_ = np.linalg.cholesky(A)
        self.alpha_ = cho_solve((self.L_, True), self.derivative_residual_standardized_)
        self.condition_number_ = float(np.linalg.cond(A))
        self.alpha_norm_ = float(np.linalg.norm(self.alpha_))
        anchor = np.array([[self.anchor_s_, self.anchor_T_]])
        anchor = (anchor - self.x_mean_)/self.x_scale_
        K_anchor = np.hstack([
            self._dK_dy(anchor, self.Z_s_, 0),
            self._dK_dy(anchor, self.Z_T_, 1),
        ])
        self.anchor_residual_standardized_ = float((K_anchor @ self.alpha_).item())

    @staticmethod
    def _combine_noise_covariances(old_covariance, new_covariance, n_old, n_new):
        """combine independent old and new field-noise covarainces. both matrices use
        ordering [q_s points, q_T points]. cross-field noise cov taken as zero because new 
        oracle calls assumed independent of previous field construction."""
        n_total = n_old + n_new
        combined = np.zeros((2 * n_total, 2 * n_total), dtype=float)
        old_s = slice(0, n_old)
        old_T = slice(n_total, n_total + n_old)
        new_s = slice(n_old, n_total)
        new_T = slice(n_total + n_old, 2 * n_total)
        combined[old_s, old_s] = old_covariance[:n_old, :n_old]
        combined[old_s, old_T] = old_covariance[:n_old, n_old:]
        combined[old_T, old_s] = old_covariance[n_old:, :n_old]
        combined[old_T, old_T] = old_covariance[n_old:, n_old:]
        combined[new_s, new_s] = new_covariance[:n_new, :n_new]
        combined[new_s, new_T] = new_covariance[:n_new, n_new:]
        combined[new_T, new_s] = new_covariance[n_new:, :n_new]
        combined[new_T, new_T] = new_covariance[n_new:, n_new:]
        return combined

    def update_posterior(self, field, *, s_query=None, T_query=None, distance_based=False):
        """add one newly built finite-difference field to the bounded posterior. (s_query, T_query)
        are queries that trigger resampling. required only when distance_based=True; if ommitted, new 
        field anchor used. distance_based: if false, we use FIFO eviction; true retains all incoming points
        and removes existing deriv centers furthest from query in Matern-scaled standardized distance. importantly,
        hyperparameters are not reoptimized; exact bounded covariance system rebuild because a field contributes
        a correlated block of q_s and q_T observations."""
        close_data = False
        if isinstance(field, (str, Path)):
            data = np.load(Path(field), allow_pickle=False)
            close_data = True
        else:
            data = field
        try:
            X_s_new = np.asarray(data["X_dq_ds"], dtype=float).reshape(-1, 2)
            d_s_new = np.asarray(data["dq_ds"], dtype=float).reshape(-1)
            X_T_new = np.asarray(data["X_dq_dT"], dtype=float).reshape(-1, 2)
            d_T_new = np.asarray(data["dq_dT"], dtype=float).reshape(-1)
            covariance_new = np.asarray(data["derivative_noise_covariance"], dtype=float)
            new_anchor = np.asarray(data["anchor_point"], dtype=float).reshape(2)
            new_anchor_q = float(data["anchor_q"])
            metadata = {}
            for key in (
                "sampling_radii",
                "local_bounds",
                "h_s",
                "h_T",
                "repeats",
                "anchor_q_variance",
                "learned_oracle_noise_variance",
                "learned_oracle_noise_std",
            ):
                if key in data:
                    metadata[key] = np.asarray(data[key])
        finally:
            if close_data:
                data.close()
        n_new = d_s_new.size
        n_old = self.dq_ds_raw_.size
        X_s_all = np.vstack([self.X_dq_ds_raw_, X_s_new])
        X_T_all = np.vstack([self.X_dq_dT_raw_, X_T_new])
        d_s_all = np.concatenate([self.dq_ds_raw_, d_s_new])
        d_T_all = np.concatenate([self.dq_dT_raw_, d_T_new])
        covariance_all = self._combine_noise_covariances(
            self.derivative_noise_covariance_raw_,
            covariance_new,
            n_old,
            n_new)
        capacity = self.max_cache_size
        total = n_old + n_new
        if total <= capacity:
            keep = np.arange(total)
        elif n_new >= capacity:
            if distance_based:
                if s_query is None and T_query is None:
                    query = new_anchor
                else:
                    s_ref, T_ref = np.broadcast_arrays(np.asarray(s_query, dtype=float), np.asarray(T_query, dtype=float))
                    query = np.array([float(np.mean(s_ref)), float(np.mean(T_ref))])
                X_new_standardized = (X_s_new - self.x_mean_) / self.x_scale_
                query_standardized = (query - self.x_mean_) / self.x_scale_
                distances = np.linalg.norm((X_new_standardized - query_standardized) / self.lengthscales_, axis=1)
                keep_new = np.argsort(distances)[:capacity]
            else:
                keep_new = np.arange(n_new - capacity, n_new)
            keep = n_old + keep_new
        else:
            old_slots = capacity - n_new
            if distance_based:
                if s_query is None and T_query is None:
                    query = new_anchor
                else:
                    s_ref, T_ref = np.broadcast_arrays(np.asarray(s_query, dtype=float), np.asarray(T_query, dtype=float))
                    query = np.array([float(np.mean(s_ref)), float(np.mean(T_ref))])
                X_old_standardized = (self.X_dq_ds_raw_ - self.x_mean_) / self.x_scale_
                query_standardized = (query - self.x_mean_) / self.x_scale_
                old_distances = np.linalg.norm((X_old_standardized - query_standardized) / self.lengthscales_, axis=1)
                keep_old = np.sort(np.argsort(old_distances)[:old_slots])
            else:
                keep_old = np.arange(n_old - old_slots, n_old)
            keep_new = np.arange(n_old, n_old + n_new)
            keep = np.concatenate([keep_old, keep_new])
        covariance_indices = np.concatenate([keep, total + keep])
        self.X_dq_ds_raw_ = X_s_all[keep].copy()
        self.dq_ds_raw_ = d_s_all[keep].copy()
        self.X_dq_dT_raw_ = X_T_all[keep].copy()
        self.dq_dT_raw_ = d_T_all[keep].copy()
        self.derivative_noise_covariance_raw_ = (covariance_all[np.ix_(covariance_indices, covariance_indices)].copy())
        # the newest field anchor becomes the local flux integration anchor
        self.anchor_s_ = float(new_anchor[0])
        self.anchor_T_ = float(new_anchor[1])
        self.anchor_q_ = new_anchor_q
        if "sampling_radii" in metadata:
            self.sampling_radii_ = np.asarray(metadata["sampling_radii"], dtype=float)
        if "local_bounds" in metadata:
            self.local_bounds_ = np.asarray(metadata["local_bounds"], dtype=float)
        if "h_s" in metadata:
            self.h_s_ = float(metadata["h_s"])
        if "h_T" in metadata:
            self.h_T_ = float(metadata["h_T"])
        if "repeats" in metadata:
            self.repeats_ = int(metadata["repeats"])
        if "anchor_q_variance" in metadata:
            self.anchor_q_variance_ = float(metadata["anchor_q_variance"])
        if "learned_oracle_noise_variance" in metadata:
            self.learned_oracle_noise_variance_ = float(metadata["learned_oracle_noise_variance"])
        if "learned_oracle_noise_std" in metadata:
            self.learned_oracle_noise_std_ = float(metadata["learned_oracle_noise_std"])
        self._rebuild_cached_posterior()
        retained_new = int(np.sum(keep >= n_old))
        dropped = int(total - keep.size)
        self.posterior_updates_ += 1
        self.total_points_added_ += retained_new
        self.total_points_dropped_ += dropped
        return {
            "n_added": retained_new,
            "n_dropped": dropped,
            "cache_size": int(self.dq_ds_raw_.size),
            "distance_based": bool(distance_based),
            "posterior_updates": int(self.posterior_updates_)}

    def _query(self, s, T):
        """broadcast physical queries and map to standardize coordinates"""
        s, T = np.broadcast_arrays(np.asarray(s, dtype=float), np.asarray(T, dtype=float))
        shape = s.shape
        X_raw = np.column_stack([s.ravel(), T.ravel()])
        X = (X_raw - self.x_mean_) / self.x_scale_
        return X_raw, X, shape

    def predict_derivatives(self, s, T):
        """return posterior means of physical dq/ds and dq/dT; cross covariances between
        query derivatives and the stacked derivative observations multiply shared posterior
        coefficient vector alpha"""
        _, X, shape = self._query(s, T)
        K_s = np.hstack([
                self._d2K_dxdy(X, self.Z_s_, 0, 0),
                self._d2K_dxdy(X, self.Z_T_, 0, 1)])
        K_T = np.hstack([
                self._d2K_dxdy(X, self.Z_s_, 1, 0),
                self._d2K_dxdy(X, self.Z_T_, 1, 1)])
        dq_ds = -self.k_ref_ + self.q_scale_ * (K_s @ self.alpha_) / self.x_scale_[0]
        dq_dT = self.q_scale_ * (K_T @ self.alpha_) / self.x_scale_[1]
        return dq_ds.reshape(shape), dq_dT.reshape(shape)

    def predict_flux(self, s, T):
        """local flux prediction using the kernel directly; namely, returns the anchored posterior
        flux without numerical integration. baseline q_a-k_ref(s-s_a) supplies physical mean. GP residual
        shifted by its value at the anchor so q(s_a, T_a) = q_a"""
        X_raw, X, shape = self._query(s, T)
        K_q = np.hstack([self._dK_dy(X, self.Z_s_, 0), self._dK_dy(X, self.Z_T_, 1)])
        baseline = self.anchor_q_ - self.k_ref_ * (X_raw[:, 0] - self.anchor_s_)
        residual = K_q @ self.alpha_ - self.anchor_residual_standardized_
        return (baseline + self.q_scale_ * residual).reshape(shape)
    
    def predict_variance(self, s, T):
        """return posterior latent variances of q, dq/ds, and dq/dT in physical units.
        for derivative quantity g with query-to-data covariance K_gd, Var[g|d] = K_gg - K_gd A^{-1} K_dg.
        flus uncertainty is computed for the anchored difference q(x) - q(x-a), so the current model 
        treats anchor_q as exact and has zeor flux variance at anchor."""
        _, X, shape = self._query(s,T)
        K_s = np.hstack([
            self._d2K_dxdy(X, self.Z_s_, 0, 0),
            self._d2K_dxdy(X, self.Z_T_, 0, 1),
        ])
        K_T = np.hstack([
            self._d2K_dxdy(X, self.Z_s_, 1, 0),
            self._d2K_dxdy(X, self.Z_T_, 1, 1),
        ])
        solved_s = cho_solve((self.L_, True), K_s.T)
        solved_T = cho_solve((self.L_, True), K_T.T)
        if self.kernel_nu == 1.5:
            derivative_prior_s = (3.0 * self.variance_ / self.lengthscales_[0] ** 2)
            derivative_prior_T = (3.0 * self.variance_ / self.lengthscales_[1] ** 2)
        else:
            # defaults kept from the nu = 2.5 case
            derivative_prior_s = ((5.0 / 3.0) * self.variance_/ self.lengthscales_[0] ** 2)
            derivative_prior_T = ((5.0 / 3.0) * self.variance_/ self.lengthscales_[1] ** 2)

        var_s_standardized = (derivative_prior_s - np.sum(K_s * solved_s.T, axis=1))
        var_T_standardized = (derivative_prior_T - np.sum(K_T * solved_T.T, axis=1))
        anchor = np.array([[self.anchor_s_, self.anchor_T_]])
        anchor = (anchor - self.x_mean_) / self.x_scale_
        K_q = np.hstack([
            self._dK_dy(X, self.Z_s_, 0),
            self._dK_dy(X, self.Z_T_, 1),
        ])
        K_anchor = np.hstack([
            self._dK_dy(anchor, self.Z_s_, 0),
            self._dK_dy(anchor, self.Z_T_, 1),
        ])
        K_delta = K_q - K_anchor
        solved_q = cho_solve((self.L_, True), K_delta.T)
        prior_flux_difference = (2.0 * self.variance_ - 2.0 * self._K(X, anchor).reshape(-1))
        var_q_standardized = (prior_flux_difference - np.sum(K_delta * solved_q.T, axis=1))
        var_q = self.q_scale_**2 * np.maximum(var_q_standardized, 0.0)
        var_dq_ds = (self.q_scale_ / self.x_scale_[0]) ** 2 * np.maximum(var_s_standardized, 0.0)
        var_dq_dT = (self.q_scale_ / self.x_scale_[1]) ** 2 * np.maximum(var_T_standardized, 0.0)
        return var_q.reshape(shape), var_dq_ds.reshape(shape), var_dq_dT.reshape(shape)
        

    def integrate_flux(self, s, T, n_quad=20):
        """reconstructs q by integrating conservative derivative field. path first integrates
        q_s from (s_a, T_a) to (s, T_a), then q_T from (s, T_a) to (s,T). GL quadrature approximates
        both line integrals. for an exactly integrable posterior, path choice changes only 
        numerical quadrature error."""
        s, T = np.broadcast_arrays(np.asarray(s, dtype=float), np.asarray(T, dtype=float))
        nodes, weights = leggauss(int(n_quad))
        q = np.empty(s.size)
        for i, (s_target, T_target) in enumerate(zip(s.ravel(), T.ravel())):
            s_nodes = 0.5 * (s_target - self.anchor_s_) * nodes
            s_nodes += 0.5 * (s_target + self.anchor_s_)
            T_nodes = np.full_like(s_nodes, self.anchor_T_)
            dq_ds, _ = self.predict_derivatives(s_nodes, T_nodes)
            integral_s = 0.5 * (s_target - self.anchor_s_) * np.dot(weights, dq_ds)
            T_nodes = 0.5 * (T_target - self.anchor_T_) * nodes
            T_nodes += 0.5 * (T_target + self.anchor_T_)
            s_nodes = np.full_like(T_nodes, s_target)
            _, dq_dT = self.predict_derivatives(s_nodes, T_nodes)
            integral_T = 0.5 * (T_target - self.anchor_T_) * np.dot(weights, dq_dT)
            q[i] = self.anchor_q_ + integral_s + integral_T
        return q.reshape(s.shape)

    def evaluate(self, s, T, integrate=False, return_variance=False):
        "provider interface returning q, dq/ds, dq/dT in physical units"
        dq_ds, dq_dT = self.predict_derivatives(s, T)
        q = self.integrate_flux(s, T) if integrate else self.predict_flux(s, T)
        if not return_variance:
            return q, dq_ds, dq_dT
        var_q, var_dq_ds, var_dq_dT = self.predict_variance(s,T)
        return q, dq_ds, dq_dT, var_q, var_dq_ds, var_dq_dT

    def physics_diagnostics(self, s_bounds, T_bounds, n=41):
        """measure diffusion-sign and conductivity-floor violations on a grid. for thermal
        flux convention used here, physical diffusion requires q_s <= 0, with effective
        conductivity k_eff = -q_s."""
        s = np.linspace(s_bounds[0], s_bounds[1], int(n))
        T = np.linspace(T_bounds[0], T_bounds[1], int(n))
        S, TT = np.meshgrid(s, T, indexing="ij")
        dq_ds, dq_dT = self.predict_derivatives(S, TT)
        return {
            "minimum_effective_diffusion": float(np.min(-dq_ds)),
            "worst_positive_dq_ds": float(max(0.0, np.max(dq_ds))),
            "positive_dq_ds_fraction": float(np.mean(dq_ds > 0.0)),
            "diffusion_floor_violation_fraction": float(np.mean(-dq_ds < self.min_conductivity)),
            "maximum_abs_dq_dT": float(np.max(np.abs(dq_dT))),
        }

"""smoke test to verify functionality of dynamic updating, fifo vs distance based."""
if __name__ == "__main__":
    data_path = (Path(__file__).resolve().parent/ "fd_derivative_field_local.npz")
    with np.load(data_path, allow_pickle=False) as data:
        initial_cache_size = int(np.asarray(data["dq_ds"]).size)
    # leave room for only part of a new 3x3 field so both update modes must evict old derivative centers.
    max_cache_size = initial_cache_size + 4
    common = {
        "kernel_nu": 1.5,
        "k_ref": 1.25,
        "min_conductivity": 0.2,
        "reg_derivative": 1e-5,
        "max_cache_size": max_cache_size,
    }
    fifo_model = DerivativeGPFluxST.from_npz(data_path, **common)
    distance_model = DerivativeGPFluxST.from_npz(data_path, **common)
    # original reconstruction check.
    s_bounds = fifo_model.local_bounds_[0]
    T_bounds = fifo_model.local_bounds_[1]
    s = np.linspace(s_bounds[0], s_bounds[1], 40)
    T = np.linspace(T_bounds[0], T_bounds[1], 40)
    S, TT = np.meshgrid(s, T, indexing="ij")
    q, dq_ds, dq_dT, var_q, var_dq_ds, var_dq_dT = fifo_model.evaluate(S, TT, return_variance=True)
    q_true = -(1.25 * (1.0 + 0.18 * TT**2) + 0.12 * S**2) * S
    dq_ds_true = -(1.25 * (1.0 + 0.18 * TT**2) + 0.36 * S**2)
    dq_dT_true = -0.45 * TT * S

    def rmse(prediction, truth):
        return float(np.sqrt(np.mean((prediction - truth) ** 2)))

    print("Initial cache size:", initial_cache_size)
    print("Maximum cache size:", max_cache_size)
    print("q RMSE:", rmse(q, q_true))
    print("dq/ds RMSE:", rmse(dq_ds, dq_ds_true))
    print("dq/dT RMSE:", rmse(dq_dT, dq_dT_true))
    print("Maximum initial derivative variance:", float(np.max(np.maximum(var_dq_ds, var_dq_dT))))

    def exact_flux(s_value, T_value):
        return -(1.25 * (1.0 + 0.18 * T_value**2) + 0.12 * s_value**2) * s_value

    def make_update_field(anchor, radius=0.04, n_side=3):
        """small in-memory field used only to exercise cache eviction."""
        s_axis = np.linspace(anchor[0] - radius, anchor[0] + radius, n_side)
        T_axis = np.linspace(anchor[1] - radius, anchor[1] + radius, n_side)
        S_new, T_new = np.meshgrid(s_axis,T_axis, indexing="ij")
        centers = np.column_stack([S_new.ravel(), T_new.ravel()])
        s_new = centers[:, 0]
        T_new = centers[:, 1]
        d_s_new = -(1.25 * (1.0 + 0.18 * T_new**2) + 0.36 * s_new**2)
        d_T_new = -0.45 * T_new * s_new
        n_new = centers.shape[0]
        covariance = 1e-6 * np.eye(2 * n_new)
        return {
            "X_dq_ds": centers,
            "dq_ds": d_s_new,
            "X_dq_dT": centers.copy(),
            "dq_dT": d_T_new,
            "derivative_noise_covariance": covariance,
            "anchor_point": np.asarray(anchor, dtype=float),
            "anchor_q": exact_flux(*anchor),
            "anchor_q_variance": np.asarray(1e-6),
            "sampling_radii": np.asarray([radius, radius]),
            "local_bounds": np.asarray([[anchor[0] - radius, anchor[0] + radius], [anchor[1] - radius, anchor[1] + radius]]),
            "h_s": np.asarray(radius / n_side),
            "h_T": np.asarray(radius / n_side),
            "repeats": np.asarray(1),
            "learned_oracle_noise_variance": np.asarray(1e-6),
            "learned_oracle_noise_std": np.asarray(1e-3),
        }

    # put the update near the upper-right side of the original patch so query-local eviction differs visibly from FIFO eviction.
    update_anchor = np.array([s_bounds[1] - 0.10 * np.ptp(s_bounds), T_bounds[1] - 0.10 * np.ptp(T_bounds)])
    update_field = make_update_field(update_anchor)
    old_points = fifo_model.X_dq_ds_raw_.copy()
    n_new = update_field["dq_ds"].size
    old_slots = max_cache_size - n_new
    n_old_dropped = initial_cache_size - old_slots
    expected_fifo_old = old_points[n_old_dropped:]
    expected_fifo_evicted = old_points[:n_old_dropped]
    old_standardized = (old_points - distance_model.x_mean_) / distance_model.x_scale_
    query_standardized = (update_anchor - distance_model.x_mean_) / distance_model.x_scale_
    old_distances = np.linalg.norm((old_standardized - query_standardized) / distance_model.lengthscales_, axis=1)
    expected_distance_indices = np.sort(np.argsort(old_distances)[:old_slots])
    expected_distance_old = old_points[expected_distance_indices]
    expected_distance_evicted = np.delete(old_points, expected_distance_indices, axis=0)
    fifo_info = fifo_model.update_posterior(update_field, distance_based=False)
    distance_info = distance_model.update_posterior(update_field, s_query=update_anchor[0], T_query=update_anchor[1], distance_based=True)
    fifo_old_retained = fifo_model.X_dq_ds_raw_[:old_slots]
    distance_old_retained = distance_model.X_dq_ds_raw_[:old_slots]
    fifo_pass = np.allclose(fifo_old_retained, expected_fifo_old)
    distance_pass = np.allclose(distance_old_retained, expected_distance_old)
    print("\nFIFO update:", fifo_info)
    print("FIFO eviction correct:", fifo_pass)
    print("FIFO evicted old points:\n", expected_fifo_evicted)
    print("\nDistance-based update:", distance_info)
    print("Distance-based eviction correct:", distance_pass)
    print("Distance-based evicted old points:\n", expected_distance_evicted)
    q_fifo, dq_ds_fifo, dq_dT_fifo = fifo_model.evaluate(S, TT)
    q_distance, dq_ds_distance, dq_dT_distance = distance_model.evaluate(S, TT)
    print("\nPost-update RMSE against exact law")
    print("FIFO: ", "q: ", rmse(q_fifo, q_true), "dq_ds: ", rmse(dq_ds_fifo, dq_ds_true), "dq_dT: ", rmse(dq_dT_fifo, dq_dT_true))
    print("Distance-based:", "q: ", rmse(q_distance, q_true), "dq_ds: ", rmse(dq_ds_distance, dq_ds_true), "dq_dT: ", rmse(dq_dT_distance, dq_dT_true))
    print("\nFIFO versus distance-based prediction RMSE")
    print("q: ", rmse(q_fifo, q_distance), "dq_ds: ", rmse(dq_ds_fifo, dq_ds_distance), "dq_dT: ", rmse(dq_dT_fifo, dq_dT_distance))
    for label, updated_model in (("FIFO", fifo_model), ("distance-based", distance_model)):
        _, _, _, _, updated_var_s, updated_var_T = updated_model.evaluate(update_anchor[0], update_anchor[1], return_variance=True)
        print(f"{label} max derivative variance at new anchor:", float(max(updated_var_s, updated_var_T)))
    if not fifo_pass or not distance_pass:
        raise RuntimeError("Eviction smoke test failed")    
  

