"""
This script is primarily for inspection purposes, if one would like to 
look through the npz file. The derivativeGP script otherwise simply uses 
the npz generated by buildFDField.py.
"""

from pathlib import Path
import numpy as np

def npz_to_csv(npz_file, csv_file=None):
    """convert saved FD deriv field from NPZ to CSV; creates two separate CSVs:
    (1) field_csv; (2) covariance_csv"""
    npz_file = Path(npz_file)
    if csv_file is None: 
        csv_file = npz_file.with_suffix(".csv")
    else:
        csv_file = Path(csv_file)
    csv_file.parent.mkdir(parents=True, exist_ok=True)
    with np.load(npz_file, allow_pickle=False) as field:
        X_s = np.asarray(field["X_dq_ds"], dtype=float)
        X_T = np.asarray(field["X_dq_dT"], dtype=float)
        dq_ds = np.asarray(field["dq_ds"], dtype=float).reshape(-1)
        dq_dT = np.asarray(field["dq_dT"], dtype=float).reshape(-1)
        covariance = np.asarray(
            field["derivative_noise_covariance"],
            dtype=float)
    n = X_s.shape[0]
    variance = np.diag(covariance)
    data = np.column_stack([
            X_s[:, 0],
            X_s[:, 1],
            dq_ds,
            dq_dT,
            variance[:n],
            variance[n:]])
    np.savetxt(
        csv_file,
        data,
        delimiter=",",
        header="s,T,dq_ds,dq_dT,var_dq_ds,var_dq_dT",
        comments="")
    covariance_csv = csv_file.with_name(csv_file.stem + "_covariance.csv")
    np.savetxt(
        covariance_csv,
        covariance,
        delimiter=",")
    return csv_file, covariance_csv 
