"""
Performs three complementary checks: 
- analytic residual jacobian correctness
    --> compare with centered finite diff jacobian of full residual
- jacobian conditioning, sensitivity to small state change 
    --> report condition number, smallest singular value, and perturbation
    amplicification at several representatitve temperature states
- newton convergence status
    --> run one simple newton method using numpy.linalg.solve and backtracking

some notes on what is reported 
1. analytic vs finite difference error is computed:
    E = ||J_analytic - J_fc||_F/||J_fd||_F
    if small -- GP derivs, units, signs and resid assembly consistent
    if large -- implementation issue with jacobian assembly
    RMK: finite diff jacobian differentiates complete resid, not just gp flux
2. condition number, and smallest sing value
3. jacobian perturbation sensitivity (jacobian_change_amplification)
    make a small perturbation deltaT and compute:
        A_J = [||J(T+deltaT) - J(T)||_F/||J(T)||_F]/[||deltaT||_2/||T||_2]
    measures if a small change in temperature state causes disproportionately large 
    change in Jacobian 
4. effective diffusion (physical correctness)
5. derivative rmse at states newton actually queries, ie calculate:
    RMSE(q_pred(s_e, T_e), q_true(s_e, T_e)) at face states generated by each temp profile
    more relevant becase (s_e, T_e) are states that actually enter the jacobian

"""

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from monotoneGPReg import MonotoneGPFluxST

# EXPERIMENT CONTROLS
seed = 42
n_train = 50
true_noise_std = 0.20
s_train_range = (-1.5, 1.5)
t_train_range = (0.5, 2.5)
reg_function = 0.0
reg_derivative = 0.0
n_restarts_optimizer = 5
n_virtual_per_axis = 50

n_elements = 20
fd_relative_step = float(np.cbrt(np.finfo(float).eps))
state_perturbation_relative = 1e-5
max_newton_iterations = 15
newton_tolerance = 1e-8
min_line_search_step = 2.0**-12

OUTPUT_DIR = Path(__file__).resolve().parent/"GPJacobianStabilityResults"

# EXACT FLUX LAW
def exact_flux(s, T):
    k0, alpha, beta = 1.25, 0.18, 0.12
    return -(k0 * (1.0 + alpha * T**2) + beta * s**2) * s


def exact_dq_ds(s, T):
    k0, alpha, beta = 1.25, 0.18, 0.12
    return -(k0 * (1.0 + alpha * T**2) + 3.0 * beta * s**2)


def exact_dq_dT(s, T):
    k0, alpha = 1.25, 0.18
    return -2.0 * k0 * alpha * T * s

# TRAINING DATA AND GP FIT
def make_training_data():
    rng = np.random.default_rng(seed)
    s_train = rng.uniform(*s_train_range, n_train)
    T_train = rng.uniform(*t_train_range, n_train)
    q_train = exact_flux(s_train, T_train) + rng.normal(
        0.0,
        true_noise_std,
        n_train,
    )
    return s_train, T_train, q_train


def fit_model(s_train, T_train, q_train):
    return MonotoneGPFluxST(
        s_train,
        T_train,
        q_train,
        noise_std=true_noise_std,
        learn_neg_flux=True,
        n_virtual_per_axis=50,
        probit_nu=1e-3,
        ep_max_iter=60,
        ep_damping=0.5,
        ep_tol=1e-5,
        jitter=1e-8,
        n_restarts_optimizer=n_restarts_optimizer,
        reg_function=reg_function,
        reg_derivative=reg_derivative,
    )

# SIMPLE DISCRETE NONLINEAR PROBLEM
def exact_temperature(x):
    return 1.3 + 0.4 * x + 0.20 * np.sin(np.pi * x)


def make_problem():
    x = np.linspace(0.0, 1.0, n_elements + 1)
    h = float(x[1] - x[0])
    T_exact = exact_temperature(x)

    s_face = np.diff(T_exact) / h
    T_face = 0.5 * (T_exact[:-1] + T_exact[1:])
    q_face = exact_flux(s_face, T_face)

    # This makes T_exact an exact root when the exact flux law is used.
    source = np.diff(q_face) / h

    return {
        "x": x,
        "h": h,
        "T_exact": T_exact,
        "T_left": float(T_exact[0]),
        "T_right": float(T_exact[-1]),
        "source": source,
    }


def full_temperature(interior_temperature, problem):
    T = np.empty(problem["x"].size, dtype=float)
    T[0] = problem["T_left"]
    T[-1] = problem["T_right"]
    T[1:-1] = np.asarray(interior_temperature, dtype=float)
    return T


def face_states(interior_temperature, problem):
    T = full_temperature(interior_temperature, problem)
    h = problem["h"]
    s_face = np.diff(T) / h
    T_face = 0.5 * (T[:-1] + T[1:])
    return T, s_face, T_face


def residual(interior_temperature, model, problem):
    _, s_face, T_face = face_states(interior_temperature, problem)
    q_face, _, _ = model.evaluate(s_face, T_face)
    return np.diff(q_face) / problem["h"] - problem["source"]


def analytic_jacobian(interior_temperature, model, problem):
    """Assemble dR/dT using the physical dq/ds and dq/dT from the GP."""
    _, s_face, T_face = face_states(interior_temperature, problem)
    _, dq_ds, dq_dT = model.evaluate(s_face, T_face)

    h = problem["h"]
    n_nodes = problem["x"].size
    n_interior = n_nodes - 2

    # Face e joins nodes e and e+1.
    dq_dleft = -dq_ds / h + 0.5 * dq_dT
    dq_dright = dq_ds / h + 0.5 * dq_dT

    J_full = np.zeros((n_interior, n_nodes), dtype=float)

    for row, node in enumerate(range(1, n_nodes - 1)):
        left_face = node - 1
        right_face = node

        # R_i = (q_right - q_left) / h - source_i.
        J_full[row, right_face] += dq_dleft[right_face] / h
        J_full[row, right_face + 1] += dq_dright[right_face] / h
        J_full[row, left_face] -= dq_dleft[left_face] / h
        J_full[row, left_face + 1] -= dq_dright[left_face] / h

    # Remove columns belonging to fixed Dirichlet nodes.
    return J_full[:, 1:-1], dq_ds, dq_dT, s_face, T_face


def finite_difference_jacobian(interior_temperature, model, problem):
    """Centered finite-difference Jacobian of the complete residual."""
    state = np.asarray(interior_temperature, dtype=float).copy()
    J = np.empty((state.size, state.size), dtype=float)

    for column in range(state.size):
        step = fd_relative_step * max(1.0, abs(state[column]))
        state_plus = state.copy()
        state_minus = state.copy()
        state_plus[column] += step
        state_minus[column] -= step

        J[:, column] = (
            residual(state_plus, model, problem)
            - residual(state_minus, model, problem)
        ) / (2.0 * step)

    return J

# JACOBIAN DIAGNOSTICS
def relative_matrix_error(A, B):
    return float(
        np.linalg.norm(A - B, ord="fro")
        / max(np.linalg.norm(B, ord="fro"), 1e-14)
    )


def representative_states(problem):
    x = problem["x"]
    exact = problem["T_exact"]
    linear = np.linspace(problem["T_left"], problem["T_right"], x.size)

    # The perturbation vanishes at both boundaries.
    perturbed = exact + 0.15 * np.sin(2.0 * np.pi * x)

    return {
        "exact_profile": exact[1:-1],
        "linear_profile": linear[1:-1],
        "perturbed_profile": perturbed[1:-1],
    }


def diagnose_state(name, state, model, problem, rng):
    R = residual(state, model, problem)
    J, dq_ds, dq_dT, s_face, T_face = analytic_jacobian(
        state,
        model,
        problem,
    )
    J_fd = finite_difference_jacobian(state, model, problem)

    singular_values = np.linalg.svd(J, compute_uv=False)
    sigma_max = float(singular_values[0])
    sigma_min = float(singular_values[-1])
    condition_number = (
        np.inf if sigma_min == 0.0 else sigma_max / sigma_min
    )

    direction = rng.normal(size=state.size)
    direction /= np.linalg.norm(direction)
    perturbation = (
        state_perturbation_relative
        * max(np.linalg.norm(state), 1.0)
        * direction
    )

    J_perturbed = analytic_jacobian(
        state + perturbation,
        model,
        problem,
    )[0]

    relative_state_change = float(
        np.linalg.norm(perturbation)
        / max(np.linalg.norm(state), 1e-14)
    )
    relative_jacobian_change = float(
        np.linalg.norm(J_perturbed - J, ord="fro")
        / max(np.linalg.norm(J, ord="fro"), 1e-14)
    )

    outside = (
        (s_face < s_train_range[0])
        | (s_face > s_train_range[1])
        | (T_face < t_train_range[0])
        | (T_face > t_train_range[1])
    )

    return {
        "state": name,
        "residual_norm": float(np.linalg.norm(R)),
        "jacobian_condition": condition_number,
        "sigma_min": sigma_min,
        "analytic_vs_fd_error": relative_matrix_error(J, J_fd),
        "relative_jacobian_change": relative_jacobian_change,
        "jacobian_change_amplification": (
            relative_jacobian_change
            / max(relative_state_change, 1e-14)
        ),
        "dq_ds_rmse_at_faces": float(
            np.sqrt(np.mean((dq_ds - exact_dq_ds(s_face, T_face)) ** 2))
        ),
        "minimum_effective_diffusion": float(np.min(-dq_ds)),
        "worst_positive_dq_ds": float(max(0.0, np.max(dq_ds))),
        "positive_dq_ds_fraction": float(np.mean(dq_ds > 0.0)),
        "maximum_abs_dq_dT": float(np.max(np.abs(dq_dT))),
        "outside_training_fraction": float(np.mean(outside)),
    }

# DIRECT SOLVE NEWTON'S METHOD
def newton_solve(name, initial_state, model, problem):
    state = np.asarray(initial_state, dtype=float).copy()
    history = []
    success = False
    reason = "maximum_iterations"

    for iteration in range(max_newton_iterations):
        R = residual(state, model, problem)
        residual_norm = float(np.linalg.norm(R))

        J, dq_ds, _, _, _ = analytic_jacobian(state, model, problem)
        singular_values = np.linalg.svd(J, compute_uv=False)
        sigma_min = float(singular_values[-1])
        condition_number = float(
            np.inf
            if sigma_min == 0.0
            else singular_values[0] / sigma_min
        )

        J_fd = finite_difference_jacobian(state, model, problem)

        row = {
            "initial_state": name,
            "iteration": iteration,
            "residual_norm": residual_norm,
            "jacobian_condition": condition_number,
            "sigma_min": sigma_min,
            "analytic_vs_fd_error": relative_matrix_error(J, J_fd),
            "minimum_effective_diffusion": float(np.min(-dq_ds)),
            "worst_positive_dq_ds": float(max(0.0, np.max(dq_ds))),
            "step_length": np.nan,
        }
        history.append(row)

        if residual_norm < newton_tolerance:
            success = True
            reason = "converged"
            break

        try:
            step = np.linalg.solve(J, -R)
        except np.linalg.LinAlgError:
            reason = "singular_jacobian"
            break

        # Minimal backtracking: only require the residual norm to decrease.
        step_length = 1.0
        accepted = False

        while step_length >= min_line_search_step:
            candidate = state + step_length * step
            candidate_norm = np.linalg.norm(
                residual(candidate, model, problem)
            )

            if np.isfinite(candidate_norm) and candidate_norm < residual_norm:
                state = candidate
                accepted = True
                break

            step_length *= 0.5

        history[-1]["step_length"] = float(step_length)

        if not accepted:
            reason = "line_search_failed"
            break

    final_residual = float(np.linalg.norm(residual(state, model, problem)))
    exact_interior = problem["T_exact"][1:-1]
    relative_solution_error = float(
        np.linalg.norm(state - exact_interior)
        / max(np.linalg.norm(exact_interior), 1e-14)
    )

    summary = {
        "initial_state": name,
        "success": success,
        "reason": reason,
        "iterations": len(history),
        "final_residual": final_residual,
        "relative_solution_error": relative_solution_error,
    }

    return state, history, summary

# REPORTING AND PLOTS
def write_csv(path, rows):
    if not rows:
        return

    with path.open("w", newline="", encoding="utf-8") as output_file:
        writer = csv.DictWriter(output_file, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def print_static_report(rows):
    header = (
        f"{'state':<20}"
        f"{'cond(J)':>13}"
        f"{'sigma_min':>13}"
        f"{'J vs FD':>13}"
        f"{'J sensitivity':>15}"
        f"{'dq/ds RMSE':>14}"
        f"{'min(-dq/ds)':>14}"
        f"{'worst +dq/ds':>15}"
    )
    print("\nStatic Jacobian diagnostics")
    print(header)
    print("-" * len(header))

    for row in rows:
        print(
            f"{row['state']:<20}"
            f"{row['jacobian_condition']:>13.4e}"
            f"{row['sigma_min']:>13.4e}"
            f"{row['analytic_vs_fd_error']:>13.4e}"
            f"{row['jacobian_change_amplification']:>15.4e}"
            f"{row['dq_ds_rmse_at_faces']:>14.4e}"
            f"{row['minimum_effective_diffusion']:>14.4e}"
            f"{row['worst_positive_dq_ds']:>15.4e}"
        )


def print_newton_report(rows):
    header = (
        f"{'initial state':<20}"
        f"{'success':>10}"
        f"{'iterations':>12}"
        f"{'final residual':>17}"
        f"{'rel. sol. err':>16}"
        f"  reason"
    )
    print("\nDirect Newton summary")
    print(header)
    print("-" * len(header))

    for row in rows:
        print(
            f"{row['initial_state']:<20}"
            f"{str(row['success']):>10}"
            f"{row['iterations']:>12d}"
            f"{row['final_residual']:>17.4e}"
            f"{row['relative_solution_error']:>16.4e}"
            f"  {row['reason']}"
        )


def plot_newton_history(histories):
    # Residual norm
    plt.figure(figsize=(8, 5))
    for name, history in histories.items():
        plt.semilogy(
            [row["iteration"] for row in history],
            [row["residual_norm"] for row in history],
            marker="o",
            label=name,
        )
    plt.xlabel("Newton iteration")
    plt.ylabel("Residual norm")
    plt.title("Direct Newton residual histories")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "newton_residual_history.png", dpi=200)
    plt.close()

    # Jacobian condition number
    plt.figure(figsize=(8, 5))
    for name, history in histories.items():
        plt.semilogy(
            [row["iteration"] for row in history],
            [row["jacobian_condition"] for row in history],
            marker="o",
            label=name,
        )
    plt.xlabel("Newton iteration")
    plt.ylabel("cond(J)")
    plt.title("Jacobian conditioning during Newton")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "newton_jacobian_condition.png", dpi=200)
    plt.close()

    # Effective diffusion
    plt.figure(figsize=(8, 5))
    for name, history in histories.items():
        plt.plot(
            [row["iteration"] for row in history],
            [row["minimum_effective_diffusion"] for row in history],
            marker="o",
            label=name,
        )
    plt.axhline(0.0, linestyle="--")
    plt.xlabel("Newton iteration")
    plt.ylabel("min(-dq/ds)")
    plt.title("Minimum effective diffusion during Newton")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "newton_effective_diffusion.png", dpi=200)
    plt.close()

# MAIN 
def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    s_train, T_train, q_train = make_training_data()
    model = fit_model(s_train, T_train, q_train)
    problem = make_problem()
    states = representative_states(problem)

    print("Learned physical noise std:", model.learned_noise_std_physical_)
    print("GP training-system condition number:", model.condition_number_)

    rng = np.random.default_rng(seed + 1)
    static_rows = [
        diagnose_state(name, state, model, problem, rng)
        for name, state in states.items()
    ]
    print_static_report(static_rows)
    write_csv(OUTPUT_DIR / "static_jacobian_metrics.csv", static_rows)

    histories = {}
    summaries = []

    for name, initial_state in states.items():
        _, history, summary = newton_solve(
            name,
            initial_state,
            model,
            problem,
        )
        histories[name] = history
        summaries.append(summary)

    print_newton_report(summaries)
    write_csv(OUTPUT_DIR / "newton_summary.csv", summaries)

    all_history_rows = [
        row
        for history in histories.values()
        for row in history
    ]
    write_csv(OUTPUT_DIR / "newton_iteration_metrics.csv", all_history_rows)
    plot_newton_history(histories)

    print(f"\nResults saved to:\n{OUTPUT_DIR}")
    return model, static_rows, summaries


if __name__ == "__main__":
    main()